// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.paperuni.demo.model;

import com.paperuni.demo.model.TdMessagePK;
import java.io.Serializable;

privileged aspect TdMessagePK_Roo_Serializable {
    
    declare parents: TdMessagePK implements Serializable;
    
    private static final long TdMessagePK.serialVersionUID = 1L;
    
}
