// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.paperuni.demo.model;

import com.paperuni.demo.model.TdOrderDataOnDemand;
import com.paperuni.demo.model.TdOrderIntegrationTest;
import com.paperuni.demo.model.TdOrderRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TdOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TdOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TdOrderIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TdOrderIntegrationTest: @Transactional;
    
    @Autowired
    TdOrderDataOnDemand TdOrderIntegrationTest.dod;
    
    @Autowired
    TdOrderRepository TdOrderIntegrationTest.tdOrderRepository;
    
    @Test
    public void TdOrderIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to initialize correctly", dod.getRandomTdOrder());
        long count = tdOrderRepository.count();
        Assert.assertTrue("Counter for 'TdOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TdOrderIntegrationTest.testFind() {
        TdOrder obj = dod.getRandomTdOrder();
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to provide an identifier", id);
        obj = tdOrderRepository.findOne(id);
        Assert.assertNotNull("Find method for 'TdOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TdOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TdOrderIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to initialize correctly", dod.getRandomTdOrder());
        long count = tdOrderRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'TdOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TdOrder> result = tdOrderRepository.findAll();
        Assert.assertNotNull("Find all method for 'TdOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TdOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TdOrderIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to initialize correctly", dod.getRandomTdOrder());
        long count = tdOrderRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TdOrder> result = tdOrderRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'TdOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TdOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TdOrderIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to initialize correctly", dod.getRandomTdOrder());
        TdOrder obj = dod.getNewTransientTdOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TdOrder' identifier to be null", obj.getId());
        try {
            tdOrderRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        tdOrderRepository.flush();
        Assert.assertNotNull("Expected 'TdOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TdOrderIntegrationTest.testDelete() {
        TdOrder obj = dod.getRandomTdOrder();
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TdOrder' failed to provide an identifier", id);
        obj = tdOrderRepository.findOne(id);
        tdOrderRepository.delete(obj);
        tdOrderRepository.flush();
        Assert.assertNull("Failed to remove 'TdOrder' with identifier '" + id + "'", tdOrderRepository.findOne(id));
    }
    
}
