// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.paperuni.demo.model;

import com.paperuni.demo.model.TdRole;
import com.paperuni.demo.model.TdRoleDataOnDemand;
import com.paperuni.demo.model.TdRoleRepository;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect TdRoleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TdRoleDataOnDemand: @Component;
    
    private Random TdRoleDataOnDemand.rnd = new SecureRandom();
    
    private List<TdRole> TdRoleDataOnDemand.data;
    
    @Autowired
    TdRoleRepository TdRoleDataOnDemand.tdRoleRepository;
    
    public TdRole TdRoleDataOnDemand.getNewTransientTdRole(int index) {
        TdRole obj = new TdRole();
        setDescription(obj, index);
        setIsActivated(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void TdRoleDataOnDemand.setDescription(TdRole obj, int index) {
        String description = "description_" + index;
        if (description.length() > 70) {
            description = description.substring(0, 70);
        }
        obj.setDescription(description);
    }
    
    public void TdRoleDataOnDemand.setIsActivated(TdRole obj, int index) {
        Boolean isActivated = Boolean.TRUE;
        obj.setIsActivated(isActivated);
    }
    
    public void TdRoleDataOnDemand.setName(TdRole obj, int index) {
        String name = "name_" + index;
        if (name.length() > 20) {
            name = name.substring(0, 20);
        }
        obj.setName(name);
    }
    
    public TdRole TdRoleDataOnDemand.getSpecificTdRole(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        TdRole obj = data.get(index);
        Integer id = obj.getId();
        return tdRoleRepository.findOne(id);
    }
    
    public TdRole TdRoleDataOnDemand.getRandomTdRole() {
        init();
        TdRole obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return tdRoleRepository.findOne(id);
    }
    
    public boolean TdRoleDataOnDemand.modifyTdRole(TdRole obj) {
        return false;
    }
    
    public void TdRoleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = tdRoleRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'TdRole' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<TdRole>();
        for (int i = 0; i < 10; i++) {
            TdRole obj = getNewTransientTdRole(i);
            try {
                tdRoleRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            tdRoleRepository.flush();
            data.add(obj);
        }
    }
    
}
