// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.paperuni.demo.model;

import com.paperuni.demo.model.TdSubjectDataOnDemand;
import com.paperuni.demo.model.TdSubjectIntegrationTest;
import com.paperuni.demo.model.TdSubjectRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TdSubjectIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TdSubjectIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TdSubjectIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TdSubjectIntegrationTest: @Transactional;
    
    @Autowired
    TdSubjectDataOnDemand TdSubjectIntegrationTest.dod;
    
    @Autowired
    TdSubjectRepository TdSubjectIntegrationTest.tdSubjectRepository;
    
    @Test
    public void TdSubjectIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to initialize correctly", dod.getRandomTdSubject());
        long count = tdSubjectRepository.count();
        Assert.assertTrue("Counter for 'TdSubject' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TdSubjectIntegrationTest.testFind() {
        TdSubject obj = dod.getRandomTdSubject();
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to provide an identifier", id);
        obj = tdSubjectRepository.findOne(id);
        Assert.assertNotNull("Find method for 'TdSubject' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TdSubject' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TdSubjectIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to initialize correctly", dod.getRandomTdSubject());
        long count = tdSubjectRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'TdSubject', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TdSubject> result = tdSubjectRepository.findAll();
        Assert.assertNotNull("Find all method for 'TdSubject' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TdSubject' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TdSubjectIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to initialize correctly", dod.getRandomTdSubject());
        long count = tdSubjectRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TdSubject> result = tdSubjectRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'TdSubject' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TdSubject' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TdSubjectIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to initialize correctly", dod.getRandomTdSubject());
        TdSubject obj = dod.getNewTransientTdSubject(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TdSubject' identifier to be null", obj.getId());
        try {
            tdSubjectRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        tdSubjectRepository.flush();
        Assert.assertNotNull("Expected 'TdSubject' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TdSubjectIntegrationTest.testDelete() {
        TdSubject obj = dod.getRandomTdSubject();
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TdSubject' failed to provide an identifier", id);
        obj = tdSubjectRepository.findOne(id);
        tdSubjectRepository.delete(obj);
        tdSubjectRepository.flush();
        Assert.assertNull("Failed to remove 'TdSubject' with identifier '" + id + "'", tdSubjectRepository.findOne(id));
    }
    
}
