// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.paperuni.demo.model;

import com.paperuni.demo.model.TdSubjectDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TdSubjectDataOnDemand_Roo_Configurable {
    
    declare @type: TdSubjectDataOnDemand: @Configurable;
    
}
