// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.paperuni.demo.model;

import com.paperuni.demo.model.TdTaskDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TdTaskDataOnDemand_Roo_Configurable {
    
    declare @type: TdTaskDataOnDemand: @Configurable;
    
}
