// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.paperuni.demo.model;

import com.paperuni.demo.model.TdTaskDataOnDemand;
import com.paperuni.demo.model.TdTaskIntegrationTest;
import com.paperuni.demo.model.TdTaskRepository;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TdTaskIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TdTaskIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TdTaskIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TdTaskIntegrationTest: @Transactional;
    
    @Autowired
    TdTaskDataOnDemand TdTaskIntegrationTest.dod;
    
    @Autowired
    TdTaskRepository TdTaskIntegrationTest.tdTaskRepository;
    
    @Test
    public void TdTaskIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'TdTask' failed to initialize correctly", dod.getRandomTdTask());
        long count = tdTaskRepository.count();
        Assert.assertTrue("Counter for 'TdTask' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TdTaskIntegrationTest.testFind() {
        TdTask obj = dod.getRandomTdTask();
        Assert.assertNotNull("Data on demand for 'TdTask' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TdTask' failed to provide an identifier", id);
        obj = tdTaskRepository.findOne(id);
        Assert.assertNotNull("Find method for 'TdTask' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TdTask' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TdTaskIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'TdTask' failed to initialize correctly", dod.getRandomTdTask());
        long count = tdTaskRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'TdTask', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TdTask> result = tdTaskRepository.findAll();
        Assert.assertNotNull("Find all method for 'TdTask' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TdTask' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TdTaskIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'TdTask' failed to initialize correctly", dod.getRandomTdTask());
        long count = tdTaskRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TdTask> result = tdTaskRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'TdTask' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TdTask' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TdTaskIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'TdTask' failed to initialize correctly", dod.getRandomTdTask());
        TdTask obj = dod.getNewTransientTdTask(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TdTask' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TdTask' identifier to be null", obj.getId());
        try {
            tdTaskRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        tdTaskRepository.flush();
        Assert.assertNotNull("Expected 'TdTask' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TdTaskIntegrationTest.testDelete() {
        TdTask obj = dod.getRandomTdTask();
        Assert.assertNotNull("Data on demand for 'TdTask' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'TdTask' failed to provide an identifier", id);
        obj = tdTaskRepository.findOne(id);
        tdTaskRepository.delete(obj);
        tdTaskRepository.flush();
        Assert.assertNull("Failed to remove 'TdTask' with identifier '" + id + "'", tdTaskRepository.findOne(id));
    }
    
}
